ads/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views

from django.conf import settings
from django.conf.urls.static import static

import post.urls

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    # path('accounts/', include('accounts.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from django.urls import path, re_path

from post.views import ProductListView, ProductDetailView, UserPostListView, ProuctByCategoryListView, \
    ProductByCountryListView, ProuctByCountryCategoryListView

app_name = 'post'

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    # Todo: count category items by country and remove c from url
    path('c/<slug:country_slug>/', ProductByCountryListView.as_view(), name='product-by-country'),
    path('category/<slug:category_slug>/', ProuctByCategoryListView.as_view(), name='product-by-category'),
    path('<slug:country_slug>/<slug:category_slug>/', ProuctByCountryCategoryListView.as_view(),
         name='product-by-country-category'),

    path('detail/<slug:country_slug>/<slug:category_slug>/<int:product_id>/<slug:slug>/', ProductDetailView.as_view(), name='detail'),

    # for Users
    path('user-post/', UserPostListView.as_view(), name='user-post'),
]

post/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import translation, timezone
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User, AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

from .media_handlers import *
from .validators import *


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                verbose_name=_('Username'),
                                related_name='profiles',
                                blank=False,
                                null=True,
                                )
    display_name = models.CharField(verbose_name=_('Display Name'), null=True, blank=True, max_length=50)
    biography = models.TextField(verbose_name=_('Biography'), null=True, blank=True)
    GENDER_CHOICES = (
        ('', _("---")),
        ('M', _('Male')),
        ('F', _('Female'))
    )
    gender = models.CharField(verbose_name=_('Gender'), choices=GENDER_CHOICES, max_length=10, default='', null=True,
                              blank=True)
    mobile = models.CharField(verbose_name=_('Mobile'), null=True, blank=True, max_length=12)
    banck_account = models.CharField(verbose_name=_('Bank Account'), null=True, blank=True, max_length=500)
    website = models.URLField(verbose_name=_('Website'), null=True, blank=True, max_length=100)
    twitter = models.CharField(verbose_name=_('Twitter'), null=True, blank=True, max_length=100)
    facebook = models.CharField(verbose_name=_('Facebook'), null=True, blank=True, max_length=100)
    linkedin = models.CharField(verbose_name=_('Linkedin'), null=True, blank=True, max_length=100)
    youtube = models.CharField(verbose_name=_('Youtube'), null=True, blank=True, max_length=100)
    google_plus = models.CharField(verbose_name=_('Google Plus'), null=True, blank=True, max_length=100)
    country = models.ForeignKey('Country', on_delete=models.SET_NULL,
                                verbose_name=_('Default country'), null=True, blank=True)

    # country = models.ForeignKey(Country, on_delete=models.SET_NULL, verbose_name=_('Country'), null=True, blank=True)
    # photo = models.FileField(
    #     null=True,
    #     blank=True,
    #     max_length=100,
    #     verbose_name=_('Your Picture'),
    #     upload_to=upload_location_picture,
    #     validators=[validate_image_extension],
    #     help_text=_('Allowed formats: jpg, png, bmp, gif.')
    # )

    def __str__(self):
        return str(self.user)

    # USERNAME_FIELD = 'user'
    # REQUIRED_FIELDS = ['user']

    # @receiver(post_save, sender=User)
    # def create_user_profile(sender, instance, created, **kwargs):
    #     if created:
    #         Profile.objects.create(user=instance)

    # @receiver(post_save, sender=User)
    # def save_user_profile(sender, instance, **kwargs):
    #     try:
    #         instance.user.save()
    #     except:
    #         user = Profile.objects.create(user=instance)

    # def __init__(self, *args, **kwargs):
    #     super(Profile, self).__init__(*args, **kwargs)
    #     self._meta.get_field('username').verbose_name = _('Username')

    # class Meta:
    #     verbose_name = "user"
    #     verbose_name_plural = "Users: Change Password"


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products', blank=True, null=True)
    title_ar = models.CharField(verbose_name=_('Title Ar'), max_length=250, null=True, blank=True, )
    title_en = models.CharField(verbose_name=_('Title En'), max_length=250, null=True, blank=True, )
    country = models.ForeignKey('Country', on_delete=models.CASCADE, blank=True, null=True)
    city = models.CharField(verbose_name=_('City'), max_length=100, null=True, blank=True, )
    slug_ar = models.SlugField(verbose_name=_('Slug Ar'), max_length=250, null=True, blank=True)
    slug = models.SlugField(verbose_name=_('Slug En'), max_length=250, null=True, blank=True)
    body_ar = models.TextField(verbose_name=_('Body Ar'), null=True, blank=True)
    body_en = models.TextField(verbose_name=_('Body En'), null=True, blank=True)
    feature_image = models.ImageField(verbose_name=_('Image'), null=True,
                                      blank=True,
                                      upload_to='pictures/',
                                      validators=[validate_file_extension])
    price = models.PositiveIntegerField(verbose_name=_('Price'), default=0, null=True, blank=True)
    allow_offer = models.PositiveIntegerField(verbose_name=_('Offer'), default=0, null=True, blank=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, blank=True, null=True,
                                 related_name='category_products')
    status = models.BooleanField(verbose_name=_('Status'), default=True)  # publish - draft or hide - rejected by admin
    rejected_reason = models.TextField(verbose_name=_('Reason'), null=True, blank=True)
    view = models.PositiveIntegerField(verbose_name=_('Viewed'), default=1 ,null=True, blank=True)
    ip_address = models.GenericIPAddressField(
        default='0.0.0.0', verbose_name=_("ip address"), null=True, blank=True)
    added_by = models.CharField(verbose_name=_('Added By'), max_length=50, null=True, blank=True)
    added_on = models.DateTimeField(verbose_name=_('Added Date'), default=timezone.now, null=True, blank=True)
    updated_by = models.CharField(verbose_name=_('Updated By'), max_length=50, null=True, blank=True)
    updated_on = models.DateTimeField(verbose_name=_('Last Updated Date'), auto_now=True, null=True, blank=True)

    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('products')
        ordering = ['-updated_on']

    @property
    def title(self):
        lang = translation.get_language()
        if lang == "ar":
            return self.title_ar
        else:
            return self.title_en

    @property
    def body(self):
        lang = translation.get_language()
        if lang == "ar":
            return self.body_ar
        else:
            return self.body_en

    def __str__(self):
        return self.title

    # @property
    # def slug(self):
    #     lang = translation.get_language()
    #     if lang == "ar":
    #         return self.slug_ar
    #     else:
    #         return self.slug_en

    def save(self, *args, **kwargs):
        # if self.slug_ar in (None, '', u''):
        self.slug_ar = slugify(self.title_ar, allow_unicode=True)
        self.slug = slugify(self.title_en)
        # if self.slug_en in (None, '', u''):
        # self.slug_en = slugify(self.title_en)
        super(Product, self).save(*args, **kwargs)

    # @staticmethod
    # def get_visitors(self):
    #     return self.view + 1

    def get_absolute_url(self, **kwargs):
        return reverse('post:detail', kwargs={'product_id':self.pk,
                                              'country_slug':self.country.slug,
                                              'category_slug':self.category.slug,
                                              'slug': self.slug })
    # Todo: return slug_en and slug_ar based on lang

    # def get_absolute_url(self, **kwargs):
    #     lang = translation.get_language()
    #     if lang == "ar":
    #         return reverse('post:detail', kwargs={'slug': self.slug_ar})
    #     if lang == "en":
    #         return reverse('post:detail', kwargs={'slug': self.slug_en})

    @staticmethod
    def get_category_products(category):
        # return Product.objects.filter(category=category).order_by('-created_date').exclude(show=False)
        return Product.objects.filter(category=category)

    @staticmethod
    def get_country_products(country):
        # return Product.objects.filter(category=category).order_by('-created_date').exclude(show=False)
        return Product.objects.filter(country=country)

    @staticmethod
    def get_country_category_products(country, category):
        return Product.objects.filter(country=country, category=category)

    # @staticmethod
    # def increase_visit_count(self, commit=False):
    #     self.view += 1
    #     if commit:
    #         self.save()

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL,
                                verbose_name=_('Product ID'),
                                related_name='images', blank=True, null=True)
    image = models.ImageField(upload_to='product_images/', verbose_name=_('Image'))

    def __str__(self):
        return self.product.title_en


class Country(models.Model):
    name_ar = models.CharField(verbose_name=_('Country Ar'), max_length=100, null=True, blank=True, )
    name_en = models.CharField(verbose_name=_('Country En'), max_length=100, null=True, blank=True, )
    slug = models.SlugField(verbose_name=_('Slug'), max_length=100, null=True, blank=True, )
    display = models.BooleanField(verbose_name=_('Display'), default=True)

    class Meta:
        verbose_name = _('country')
        verbose_name_plural = _('countries')

    @property
    def country(self):
        lang = translation.get_language()
        if lang == "ar":
            return self.name_ar
        else:
            return self.name_en

    def __str__(self):
        return self.country if self.country else str(self.pk)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name_en)
        super(Country, self).save(*args, **kwargs)

    @staticmethod
    def get_country_by_slug(slug):
        try:
            return Country.objects.get(slug=slug)
        except:
            pass


class Category(models.Model):
    name_ar = models.CharField(verbose_name=_('Category Name Ar'), max_length=100, null=True, blank=True)

post/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Count, F
from django.shortcuts import render
from django.utils import translation
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView
from .models import Product, Category, Country


class ProductListView(ListView):
    model = Product
    template_name = 'ads/home.html'
    context_object_name = 'list_ads'
    paginate_by = 10

    def get_queryset(self):
        lang = translation.get_language()
        if lang == "ar":
            return Product.objects.filter(Q(title_ar__isnull=False))
        elif lang == 'en':
            return Product.objects.filter(Q(title_en__isnull=False))
        else:
            return Product.objects.none()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['categories'] = Category.get_categories()
        return context


class ProductByCountryListView(ProductListView):
    def get_queryset(self):
        self.country = Country.get_country_by_slug(self.kwargs['country_slug'])
        products = Product.get_country_products(self.country)
        return products


class ProuctByCategoryListView(ProductListView):
    def get_queryset(self):
        self.category = Category.get_category_by_slug(self.kwargs['category_slug'])
        products = Product.get_category_products(self.category)
        return products


class ProuctByCountryCategoryListView(ProductListView):
    def get_queryset(self):
        self.country = Country.get_country_by_slug(self.kwargs['country_slug'])
        self.category = Category.get_category_by_slug(self.kwargs['category_slug'])
        products = Product.get_country_category_products(self.country, self.category)
        return products


class ProductDetailView(DetailView):
    model = Product
    template_name = 'ads/product-detail.html'

    def get_object(self):
        product = super().get_object()
        print(product.view, 'Breack')
        product.view += 1
        product.save()
        # Todo: why increment by 2?! and use cache every 30 second
        return product

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        # context['visitors'] = Product.increase_visit_count(commit=True)
        return context


class UserPostListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'ads/user_post_list.html'

    def get_queryset(self):
        return Product.objects.filter(user=self.request.user)

post/templates/_category_menu.html
{% load i18n staticfiles %}

<!-- menu start -->
<nav id="menu-1" class="mega-menu">
    <!-- menu list items container -->
    <section class="menu-list-items">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <!-- menu logo -->
                    <ul class="menu-logo">
                        <li>
                            <a href="{% url 'post:home' %}"><img src="{% static 'images/logo.png' %}" alt="logo">
                            </a>
                        </li>
                    </ul>
                    <!-- menu links -->
                    <ul class="menu-links">
                        <!-- active class -->
                        <li>
                            <a>Home</a>
                        </li>

                        {% for category in menu_list %}
                            {% if request.path %}
                                <li class="nav-item active">
                                    {% else %}
                                <li class="nav-item">
                            {% endif %}
                        <a class="nav-link" href="{% url 'post:product-by-category' category.slug %}"><i
                                class="{{ category.icon }}" aria-hidden="true"></i> {{ category.category_name }}
                            <span class="sr-only">(current)</span></a>
                        </li>
                        {% endfor %}

                        <li>
                            <a>Home</a>
                        </li>
                        <li><a href="contact.html">Contact</a></li>
                    </ul>
                    <ul class="menu-search-bar">
                        <li>
                            <a href="post-ad-1.html" class="btn btn-light"><i class="fa fa-plus"
                                                                              aria-hidden="true"></i> Post Free
                                Ad</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
</nav>
<!-- menu end -->

post/templates/base.html
<!DOCTYPE html>
{% load i18n staticfiles %}
{% load menu_tag %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{% trans 'en' %}">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- =-=-=-=-=-=-= Bootstrap CSS Style =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- =-=-=-=-=-=-= Template CSS Style =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- =-=-=-=-=-=-= Font Awesome =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" type="text/css">
    <!-- =-=-=-=-=-=-= Flat Icon =-=-=-=-=-=-= -->
    <link href="{% static 'css/flaticon.css' %}" rel="stylesheet">
    <!-- =-=-=-=-=-=-= Et Line Fonts =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/et-line-fonts.css' %}" type="text/css">
    <!-- =-=-=-=-=-=-= Menu Drop Down =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/forest-menu.css' %}" type="text/css">
    <!-- =-=-=-=-=-=-= Animation =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" type="text/css">
    <!-- =-=-=-=-=-=-= Select Options =-=-=-=-=-=-= -->
    <link href="{% static 'css/select2.min.css' %}" rel="stylesheet"/>
    <!-- =-=-=-=-=-=-= noUiSlider =-=-=-=-=-=-= -->
    <link href="{% static 'css/nouislider.min.css' %}" rel="stylesheet">
    <!-- =-=-=-=-=-=-= Listing Slider =-=-=-=-=-=-= -->
    <link href="{% static 'css/slider.css' %}" rel="stylesheet">
    <!-- =-=-=-=-=-=-= Owl carousel =-=-=-=-=-=-= -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.css' %}">
    <!-- =-=-=-=-=-=-= Check boxes =-=-=-=-=-=-= -->
    <link href="{% static 'skins/minimal/minimal.css' %}" rel="stylesheet">
    <!-- =-=-=-=-=-=-= Responsive Media =-=-=-=-=-=-= -->
    <link href="{% static 'css/responsive-media.css' %}" rel="stylesheet">
    <!-- =-=-=-=-=-=-= Template Color =-=-=-=-=-=-= -->
    <link rel="stylesheet" id="color" href="{% static 'css/colors/red.css' %}">
    <!-- =-=-=-=-=-=-= For Style Switcher =-=-=-=-=-=-= -->
    <link rel="stylesheet" id="theme-color" type="text/css" href="#"/>
    <!-- JavaScripts -->
    <script src="{% static 'js/modernizr.js' %}"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->

    {% if LANGUAGE_CODE == 'ar' %}
        <link href="{% static 'css/bootstrap-rtl.css' %}" rel="stylesheet">
        <link href="{% static 'css/style-rtl.css' %}" rel="stylesheet">
    {% endif %}

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Ads</title>
    {% endif %}

    {% block head %}
    {% endblock %}
</head>

<body>
<!-- =-=-=-=-=-=-= Light Header =-=-=-=-=-=-= -->
<div class="colored-header">
    <!-- Top Bar -->
    <div class="header-top">
        <div class="container">
            <div class="row">
                <!-- Header Top Left -->
                <div class="header-top-left col-md-8 col-sm-6 col-xs-12 hidden-xs">
                    <ul class="listnone">
                        <li><a href="about.html"><i class="fa fa-heart-o" aria-hidden="true"></i> About</a></li>
                        <li><a href="faqs.html"><i class="fa fa-folder-open-o" aria-hidden="true"></i> FAQS</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false"><i class="fa fa-globe" aria-hidden="true"></i>
                                Language
                                <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/en">English</a></li>
                                <li><a href="/ar">Arabic</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- Header Top Right Social -->
                <div class="header-right col-md-4 col-sm-6 col-xs-12 ">
                    <div class="pull-right">
                        <ul class="listnone">
                            {% if not user.is_authenticated %}
                                <li><a href="{% url 'login' %}"><i class="fa fa-sign-in"></i> Log in</a></li>
                                <li><a href="register.html"><i class="fa fa-unlock" aria-hidden="true"></i> Register</a>
                                </li>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                       aria-haspopup="true" aria-expanded="false"><i class="icon-profile-male"
                                                                                     aria-hidden="true"></i> {{ user }}
                                        <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="profile.html">User Profile</a></li>
                                        <li><a href="profile-2.html">User Profile 2</a></li>
                                        <li><a href="archives.html">Archives</a></li>
                                        <li><a href="active-ads.html">Active Ads</a></li>
                                        <li><a href="pending-ads.html">Pending Ads</a></li>
                                        <li><a href="favourite.html">Favourite Ads</a></li>
                                        <li><a href="messages.html">Message Panel</a></li>
                                        <li><a href="deactive.html">Account Deactivation</a></li>
                                    </ul>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Top Bar End -->
    <!-- Navigation Menu -->
    <div class="clearfix"></div>
    <!-- menu start -->
    {% get_category_menu %}
    <!-- menu end -->
</div>
<!-- Navigation Menu End -->
<!-- =-=-=-=-=-=-= Light Header End  =-=-=-=-=-=-= -->


<div class="container">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.level_tag }}"{% endif %}>{{ message }}</div>
            {% empty %}
                No list
            {% endfor %}
        </ul>
    {% endif %}
</div>

<!-- Main Content Area -->
<div class="main-content-area clearfix">
    <!-- =-=-=-=-=-=-= Trending Ads =-=-=-=-=-=-= -->
    <section class="custom-padding gray">
        <!-- Main Container -->
        <div class="container">
            {% block content %}

            {% endblock %}
        </div>
    </section>
</div>
<!-- Post Ad Sticky -->
<a href="#" class="sticky-post-button hidden-xs">
         <span class="sell-icons">
         <i class="flaticon-transport-9"></i>
         </span>
    <h4>SELL</h4>
</a>
<!-- Back To Top -->
<a href="#0" class="cd-top">Top</a>
<!-- Product Preview Popup -->
<!-- =-=-=-=-=-=-= FOOTER =-=-=-=-=-=-= -->
<footer>
    <!-- Footer Content -->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-md-3  col-sm-6 col-xs-12">
                    <!-- Info Widget -->
                    <div class="widget">
                        <div class="logo"><img alt="" src="{% static 'images/logo-1.png' %}"></div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et dolor eget erat
                            fringilla port.</p>
                        <ul>
                            <li><img src="{% static 'images/appstore.png' %}" alt=""></li>
                            <li><img src="{% static 'images/googleplay.png' %}" alt=""></li>
                        </ul>
                    </div>
                    <!-- Info Widget Exit -->
                </div>
                <div class="col-md-3  col-sm-6 col-xs-12">
                    <!-- Follow Us -->
                    <div class="widget socail-icons">
                        <h5>Follow Us</h5>
                        <ul>
                            <li><a class="fb" href=""><i class="fa fa-facebook"></i></a><span>Facebook</span>
                            </li>
                            <li><a class="twitter" href=""><i class="fa fa-twitter"></i></a><span>Twitter</span>
                            </li>
                            <li>
                                <a class="linkedin" href=""><i class="fa fa-linkedin"></i></a><span>Linkedin</span>
                            </li>
                            <li>
                                <a class="googleplus" href=""><i class="fa fa-google-plus"></i></a><span>Google+</span>
                            </li>
                        </ul>
                    </div>
                    <!-- Follow Us End -->
                </div>
                <div class="col-md-6  col-sm-6 col-xs-12">
                    <!-- Newslatter -->
                    <div class="widget widget-newsletter">
                        <h5>Singup for Weekly Newsletter</h5>
                        <div class="fieldset">
                            <p>We may send you information about related events, webinars, products and services which
                                we believe.</p>
                            <form>
                                <input class="" value="Enter your email address" type="text">
                                <input class="submit-btn" name="submit" value="Submit" type="submit">
                            </form>
                        </div>
                    </div>
                    <!-- Newslatter -->
                </div>
            </div>
        </div>
    </div>
    <!-- Copyrights -->
    <div class="copyrights">
        <div class="container">
            <div class="copyright-content">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <p>© 2017 AForest All rights reserved. Design by {% now "Y" %}. </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- =-=-=-=-=-=-= FOOTER END =-=-=-=-=-=-= -->
<!-- =-=-=-=-=-=-= JQUERY =-=-=-=-=-=-= -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap Core Css  -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Jquery Easing -->
<script src="{% static 'js/easing.js' %}"></script>
<!-- Menu Hover  -->
<script src="{% static 'js/forest-megamenu.js' %}"></script>
<!-- Jquery Appear Plugin -->
<script src="{% static 'js/jquery.appear.min.js' %}"></script>
<!-- Numbers Animation   -->
<script src="{% static 'js/jquery.countTo.js' %}"></script>
<!-- Jquery Smooth Scroll  -->
<script src="{% static 'js/jquery.smoothscroll.js' %}"></script>
<!-- Jquery Select Options  -->
<script src="{% static 'js/select2.min.js' %}"></script>
<!-- noUiSlider -->
<script src="{% static 'js/nouislider.all.min.js' %}"></script>
<!-- Carousel Slider  -->
<script src="{% static 'js/carousel.min.js' %}"></script>
<script src="{% static 'js/slide.js' %}"></script>
<!-- Image Loaded  -->
<script src="{% static 'js/imagesloaded.js' %}"></script>
<script src="{% static 'js/isotope.min.js' %}"></script>
<!-- CheckBoxes  -->
<script src="{% static 'js/icheck.min.js' %}"></script>
<!-- Jquery Migration  -->
<script src="{% static 'js/jquery-migrate.min.js' %}"></script>
<!-- Sticky Bar  -->
<script src="{% static 'js/theia-sticky-sidebar.js' %}"></script>
<!-- Style Switcher -->
<script src="{% static 'js/color-switcher.js' %}"></script>
<!-- Template Core JS -->
<script src="{% static 'js/custom.js' %}"></script>

{% block js %}
{% endblock js %}
</body>
</html>